/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReferensiRouteImport } from './routes/referensi'
import { Route as PredictRouteImport } from './routes/predict'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FoodsRouteImport } from './routes/foods'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ChatbotRouteImport } from './routes/chatbot'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PredictIndexRouteImport } from './routes/predict.index'
import { Route as PredictResultRouteImport } from './routes/predict.result'
import { Route as PredictResultIndexRouteImport } from './routes/predict.result.index'
import { Route as PredictResultMenuSlugRouteImport } from './routes/predict.result.menu.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferensiRoute = ReferensiRouteImport.update({
  id: '/referensi',
  path: '/referensi',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictRoute = PredictRouteImport.update({
  id: '/predict',
  path: '/predict',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsRoute = FoodsRouteImport.update({
  id: '/foods',
  path: '/foods',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotRoute = ChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictIndexRoute = PredictIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PredictRoute,
} as any)
const PredictResultRoute = PredictResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => PredictRoute,
} as any)
const PredictResultIndexRoute = PredictResultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PredictResultRoute,
} as any)
const PredictResultMenuSlugRoute = PredictResultMenuSlugRouteImport.update({
  id: '/menu/$slug',
  path: '/menu/$slug',
  getParentRoute: () => PredictResultRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/chatbot': typeof ChatbotRoute
  '/faq': typeof FaqRoute
  '/foods': typeof FoodsRoute
  '/login': typeof LoginRoute
  '/predict': typeof PredictRouteWithChildren
  '/referensi': typeof ReferensiRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/predict/result': typeof PredictResultRouteWithChildren
  '/predict/': typeof PredictIndexRoute
  '/predict/result/': typeof PredictResultIndexRoute
  '/predict/result/menu/$slug': typeof PredictResultMenuSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/chatbot': typeof ChatbotRoute
  '/faq': typeof FaqRoute
  '/foods': typeof FoodsRoute
  '/login': typeof LoginRoute
  '/referensi': typeof ReferensiRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/predict': typeof PredictIndexRoute
  '/predict/result': typeof PredictResultIndexRoute
  '/predict/result/menu/$slug': typeof PredictResultMenuSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/chatbot': typeof ChatbotRoute
  '/faq': typeof FaqRoute
  '/foods': typeof FoodsRoute
  '/login': typeof LoginRoute
  '/predict': typeof PredictRouteWithChildren
  '/referensi': typeof ReferensiRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/predict/result': typeof PredictResultRouteWithChildren
  '/predict/': typeof PredictIndexRoute
  '/predict/result/': typeof PredictResultIndexRoute
  '/predict/result/menu/$slug': typeof PredictResultMenuSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calculator'
    | '/chatbot'
    | '/faq'
    | '/foods'
    | '/login'
    | '/predict'
    | '/referensi'
    | '/register'
    | '/sitemap.xml'
    | '/predict/result'
    | '/predict/'
    | '/predict/result/'
    | '/predict/result/menu/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calculator'
    | '/chatbot'
    | '/faq'
    | '/foods'
    | '/login'
    | '/referensi'
    | '/register'
    | '/sitemap.xml'
    | '/predict'
    | '/predict/result'
    | '/predict/result/menu/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calculator'
    | '/chatbot'
    | '/faq'
    | '/foods'
    | '/login'
    | '/predict'
    | '/referensi'
    | '/register'
    | '/sitemap.xml'
    | '/predict/result'
    | '/predict/'
    | '/predict/result/'
    | '/predict/result/menu/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalculatorRoute: typeof CalculatorRoute
  ChatbotRoute: typeof ChatbotRoute
  FaqRoute: typeof FaqRoute
  FoodsRoute: typeof FoodsRoute
  LoginRoute: typeof LoginRoute
  PredictRoute: typeof PredictRouteWithChildren
  ReferensiRoute: typeof ReferensiRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referensi': {
      id: '/referensi'
      path: '/referensi'
      fullPath: '/referensi'
      preLoaderRoute: typeof ReferensiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predict': {
      id: '/predict'
      path: '/predict'
      fullPath: '/predict'
      preLoaderRoute: typeof PredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods': {
      id: '/foods'
      path: '/foods'
      fullPath: '/foods'
      preLoaderRoute: typeof FoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot': {
      id: '/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof ChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predict/': {
      id: '/predict/'
      path: '/'
      fullPath: '/predict/'
      preLoaderRoute: typeof PredictIndexRouteImport
      parentRoute: typeof PredictRoute
    }
    '/predict/result': {
      id: '/predict/result'
      path: '/result'
      fullPath: '/predict/result'
      preLoaderRoute: typeof PredictResultRouteImport
      parentRoute: typeof PredictRoute
    }
    '/predict/result/': {
      id: '/predict/result/'
      path: '/'
      fullPath: '/predict/result/'
      preLoaderRoute: typeof PredictResultIndexRouteImport
      parentRoute: typeof PredictResultRoute
    }
    '/predict/result/menu/$slug': {
      id: '/predict/result/menu/$slug'
      path: '/menu/$slug'
      fullPath: '/predict/result/menu/$slug'
      preLoaderRoute: typeof PredictResultMenuSlugRouteImport
      parentRoute: typeof PredictResultRoute
    }
  }
}

interface PredictResultRouteChildren {
  PredictResultIndexRoute: typeof PredictResultIndexRoute
  PredictResultMenuSlugRoute: typeof PredictResultMenuSlugRoute
}

const PredictResultRouteChildren: PredictResultRouteChildren = {
  PredictResultIndexRoute: PredictResultIndexRoute,
  PredictResultMenuSlugRoute: PredictResultMenuSlugRoute,
}

const PredictResultRouteWithChildren = PredictResultRoute._addFileChildren(
  PredictResultRouteChildren,
)

interface PredictRouteChildren {
  PredictResultRoute: typeof PredictResultRouteWithChildren
  PredictIndexRoute: typeof PredictIndexRoute
}

const PredictRouteChildren: PredictRouteChildren = {
  PredictResultRoute: PredictResultRouteWithChildren,
  PredictIndexRoute: PredictIndexRoute,
}

const PredictRouteWithChildren =
  PredictRoute._addFileChildren(PredictRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalculatorRoute: CalculatorRoute,
  ChatbotRoute: ChatbotRoute,
  FaqRoute: FaqRoute,
  FoodsRoute: FoodsRoute,
  LoginRoute: LoginRoute,
  PredictRoute: PredictRouteWithChildren,
  ReferensiRoute: ReferensiRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
